### ISSUE TITLE
mpv hangs while playing videos from NAS.

### ISSUE THREAD

**Issue by spinktvis** [ahjolinna/mpv-conf#5] opened 2016-12-20 18:23 UTC
Great stuff, love the quality of the presets, and the extra scripts. Had to comment out all the cache options in the mpv.conf files though else mpv would hang randomly when playing videos from my NAS all the time. With mpv handling the cache by itself, it is working flawlesly. 

Not sure if this is actually an issue with the mpv.conf cache settings provided or with mpv itself.

I'd like to narrow down the issue further. Any suggestion on where to go from here?

**Comment by ahjolinna** [comment] 2016-12-22 17:21
you can check if its the "streamcache.lua" script that is the cause of the problem by commenting it out (in mpv.conf), and then you can also enable those other cache settings that I have disable: 

```
cache-initial=1000
cache-seek-min=2000
cache-secs=30
```

**Comment by ahjolinna** [comment] 2017-01-14 14:55
This issue should be fixed now as I have removed the cache script(, at least for a while as it's little bit broken with 0.23+)

**Closed as completed** 2017-01-14 14:55 UTC
